// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeTULZDMtQVxRpt8EBbbAS9hBqwMGTBRg',
    appId: '1:1079437853454:web:1bfeac236bbb87346d4d5f',
    messagingSenderId: '1079437853454',
    projectId: 'qr-generator-1fd14',
    authDomain: 'qr-generator-1fd14.firebaseapp.com',
    storageBucket: 'qr-generator-1fd14.appspot.com',
    measurementId: 'G-W81F4PXY5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv1-Gio5dVVB9PtRFRtmFz7cS1RNoXN_o',
    appId: '1:1079437853454:android:a45926cfea165ae76d4d5f',
    messagingSenderId: '1079437853454',
    projectId: 'qr-generator-1fd14',
    storageBucket: 'qr-generator-1fd14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnVRVEFEzvfIgvbMZPWPGixMeh5csg6GA',
    appId: '1:1079437853454:ios:c14e3656c912a2d96d4d5f',
    messagingSenderId: '1079437853454',
    projectId: 'qr-generator-1fd14',
    storageBucket: 'qr-generator-1fd14.appspot.com',
    iosClientId: '1079437853454-k477kjb8gqbs9daa7dqc16p6tuklaq7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCodeGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnVRVEFEzvfIgvbMZPWPGixMeh5csg6GA',
    appId: '1:1079437853454:ios:c14e3656c912a2d96d4d5f',
    messagingSenderId: '1079437853454',
    projectId: 'qr-generator-1fd14',
    storageBucket: 'qr-generator-1fd14.appspot.com',
    iosClientId: '1079437853454-k477kjb8gqbs9daa7dqc16p6tuklaq7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCodeGenerator',
  );
}
